version: '3'
      
services:

  maprinstaller:
    image: maprinstaller
    env_file:
      - mapr-installer/installer.env
    ports:
      - "9443:9443"
    tty: true
    
  centos7:
    image: maprcentos
    tty: true
    